apiVersion: v1
kind: Pod
metadata:
  name: my-ip-app-volume
spec:
  containers:
  - name: ip-app
    image: ankit969/nginx:2.0.0
    ports:
    - containerPort: 80
    volumeMounts:
    - name: my-volume
      mountPath: '/app/volume'

  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc
