apiVersion: v1
kind: Pod
metadata:
  name: my-ip-app-local
spec:
  containers:
  - name: ip-app
    image: ankit969/nginx:2.0.0
    ports:
    - containerPort: 80
    volumeMount:
    - name: my-volume
      mountPath: '/app/volume/'
  volume:
    name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc
