apiVersion: v1
<<<<<<< HEAD
kind: PersistentVolumeClaim
=======
kind: persistentVolumeClaim
>>>>>>> e3997470912922cbb32606d76a8ad77feb1b6db1
metadata:
  name: my-pvc
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
