apiVersion: rbac.authorization.k8s.io/v1
kind: clusterRole
metadata:
  name: k8s-sa-role
  namespace: default
rules:
  apiGroup: [""]
  resources: ["deployments"]
  verbs: ["list", "update", "create", "delete"]
