apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update-deployment
spec:
  replicas: 14
  selector:
    matchLabels:
      app: nginx-server
  strategy:
    type: RollingUpdate
    rollinfUpdate:
    maxUnavailable: 40%
    maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
