apiVersion: v1
kind: Pod
metadata:
  name: my-ip-app
spec:
  containers:
  - name: ip-app
    image: ankit969/nginx:2.0.0
    ports:
    - containerPort: 80
    env:
    - name: DB_URL
      valueFrom:
      secretKeyRef:
        name: my-secret
        key: db_url
    - name: DB_UNAME
      valueFrom:
      secretKeyRef:
        name: my-secret
        key: db_username
    - name: DB_PASS
      valueFrom:
      secretKeyRef:
        name: my-secret
        key: db:password
