apiVersion: v1
kind: Pod
metadata:
  name: my-ip-app
spec:
  containers:
  - name: ip-app
    image: ankit969/nginx:2.0.0
    ports:
    - containerPort: 80
    env:
    - name: ENVIRONMENT
      valueFrom:
        configMapKeyRef:
          name: my-confimap
          key: env
    - name: APP_NAME
      valueFrom:
        configMapKeyRef:
          name: my-confimap
          key: app
